module Godot
  module Mixins
    module  NilClass include _ToGodot[Variant] def nonzero?: () -> false end
    class ::NilClass include NilClass end
    
    module  TrueClass include _ToGodot[Variant] def nonzero?: () -> true end
    class ::TrueClass include TrueClass end
    
    module  FalseClass include _ToGodot[Variant] def nonzero?: () -> false end
    class ::FalseClass include FalseClass end
    
    module  Integer include _ToGodot[Variant] end
    class ::Integer include Integer end
    
    module  Float include _ToGodot[Variant] end
    class ::Float include Float end
    
    module  String include _ToGodot[Godot::String] end
    class ::String include String end
    
    module  Symbol include _ToGodot[StringName] end
    class ::Symbol include Symbol end
    
    module  Hash include _ToGodot[Dictionary] end
    class ::Hash[unchecked out K, unchecked out V] include Hash end
  end
end
