module Godot
  # until we have RBS integration
  class ScriptLanguage < Object
  end
  class RubyLanguage < ScriptLanguage
    
    def _get_name: () -> ::String
    def _get_type: () -> ::String
    def _get_extension: () -> ::String
    def _get_recognized_extensions: () -> PackedStringArray
    def _get_comment_delimiters: () -> PackedStringArray
    def _get_string_delimiters: () -> PackedStringArray
    def _can_inherit_from_file: () -> bool
    def _has_named_classes: () -> bool
    
    module Autoloads
      public def self.remove_const: (interned name) -> top
    end
    #def _add_global_constant: [T < variant_like] (interned name, T value) -> T
      # https://github.com/ruby/rbs/issues/1471
    def _add_global_constant: (interned name, variant_like value) -> variant_like
    def _add_named_global_constant: (interned name, variant_like value) -> variant_like
    def _remove_named_global_constant: (interned name) -> top
  end
  
  include RubyLanguage::Autoloads
end
