module Godot
  interface _ToGodot[out G < Variant] def to_godot: () -> G end
  
  type variant = Variant | bool?
  type variant_like = Kernel & _ToGodot[Variant]
  class Variant
    include Godot
    VARIANT_TYPE: Integer
    
    def self.allocate: () -> instance
    private def initialize_copy: (instance other) -> void
    
    def initialize: (*variant_like args) -> void
    def godot_send: (interned meth, *variant_like args) -> variant
    
    def [] : (variant_like key) -> variant
    def get: (variant_like key) -> variant?
    def []=: (variant_like key, variant_like value) -> variant
    def set: (variant_like key, variant_like value) -> variant?
    
    def has_method: (interned name) -> bool
    def method_missing: (variant_like name, *variant_like args) -> variant
    
    def to_godot: () -> self
    def nonzero?: () -> bool
  end
end
