module Godot
  
  class String < Variant
    VARIANT_TYPE: 4
    def to_s: () -> ::String
    def to_str: () -> ::String
  end

  class StringName < Variant
    VARIANT_TYPE: 21
    def to_s: () -> ::String
    def to_str: () -> ::String
    def to_sym: () -> Symbol
  end
  
  class Object < Variant
    VARIANT_TYPE: 24
    alias call godot_send
  end
  
end
