module Godot
  
  class Int < Variant
  end
  
  class Float < Variant
  end
  
  class String < Variant
    VARIANT_TYPE: 4
    def to_s: () -> ::String
    def to_str: () -> ::String
  end

  class StringName < Variant
    VARIANT_TYPE: 21
    def to_s: () -> ::String
    def to_str: () -> ::String
    def to_sym: () -> Symbol
  end
  
  class Vector2 < Variant
  end
  
  class Vector3 < Variant
  end
  
  class Color < Variant
  end
  
  class Dictionary < Variant
  end
  
  class Object < Variant
    VARIANT_TYPE: 24
    RUBY_SCRIPT: RubyScript[Object]? # https://github.com/soutaro/steep/issues/916
    def self.base_class_name: () -> StringName
    def self.allocate: ...
    def initialize: () -> void
    private def self.__godot_bind: (String name, Integer hash) -> Symbol
  end
  
end
