module Godot
  
  class String < Variant
    VARIANT_TYPE: 4
    def to_s: () -> String
    def to_str: () -> String
  end
  
  class Object < Variant
    VARIANT_TYPE: 24
    alias call godot_send
  end
  
  def self.const_missing: (Symbol name) -> singleton(Object)
end
