module Godot
  interface _ToGodot[out G < Variant] def to_godot: () -> G end
  
  type variant = Variant | bool?
  type variant_like = Object & _ToGodot[Variant]
  class Variant
    VARIANT_TYPE: Integer
    
    def self.allocate: () -> instance
    
    private def __godot_send__: (interned? meth, Array[variant_like] args) -> variant
    
    def initialize: (*variant_like args) -> void
    def godot_send: (interned meth, *variant_like args) -> variant
    
    def to_godot: () -> self
    def nonzero?: () -> bool
  end
end
